eureka:
  client:
    serviceUrl:
      defaultZone: ${REGISTRY_SERVICE_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_SERVICE_URI:http://localhost:9411/api/v2/spans}
