eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

okta:
  oauth2:
    issuer: https://dev-64868999.okta.com/oauth2/default
    audience: api://default
