eureka:
  client:
    serviceUrl:
      defaultZone: ${REGISTRY_SERVICE_URI:http://registry-service:8761/eureka}

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_SERVICE_URI:http://zipkin:9411}
